### PR TITLE
Add Web Audio support

### PR DESCRIPTION
**Pull request by geloescht**
This branch adds support for audio nodes by providing a thin layer over the Web Audio API that is implemented in modern Firefox and Webkit browsers. These nodes currently do not support spreading.

### CODE REVIEW

**Comment by andrewfriend** [comment]
Excellent news :)

**Comment by zauner** [comment]
Well that's indeed excellent news. Also: great job with the clever implementation!

Funny/tragic coinsidence is, that @artofmus from [this forum thread](http://vvvvjs.com/forum/read.php?3,271) just finished a first draft of his version of a WebAudio implementation, when we discovered the pull request. I think it would be great if @artofmus joined the discussion, and if we joined forces for future improvements.

Regarding the audio param pins, which should also be connected to audio signals: I think we need a special pin type VVVV.PinTypes.AudioParam for this. It should work as a value pin in the editor, but should also accept incoming audio signals. I will need to have a look into this, as VVVV.js at the moment does not support subtypes, as VVVV does.

**Comment by geloescht** [comment]
Thanks for the pull! :)
As for @artofmus's implementation, I was not aware of that. I wasn't even aware of the whole vvvv.js forum. Well, I am looking forward to a collaboration!
Here are the few loose ends I think should be tied before we call this implementation final:
1. The AudioParam issue. Can input pins support multiple 
2. Spreading. Should we create multiple API nodes inside a VVVV.js node when we have multiple input slices? When should we downmix spreaded audio streams?
3. Mixing. Right now there is no Mixer node because there is no 1:1 mapping to a Web Audio node. I'd like to take a look at VAudio before tackling this.

**Comment by zauner** [comment]
Yes, these were the 3 points we also identified. As each of these are quite complex i opened separate issues for further discussion.

**Pull request merged**
